acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('lgout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('pdfread/', include('pdfread.urls')),
    path('vote/', include('vote.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"

urlpatterns = [
path('index/', views.index, name="index"),
path('detail/<tpk>', views.detail, name="detail"),
path('vote/<tpk>', views.vote, name="vote"),
path('cancel/<tpk>', views.cancel, name="cancel"),
path('create/', views.create, name="create"),
]

vote/models.py
from distutils.command.upload import upload
from statistics import mode
from tkinter.tix import Tree
from django.db import models
from acc.models import User

class Topic(models.Model):
    subject = models.CharField(max_length=200)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject
    def summary(self):
        if len(self.content) > 20:
            return f"self.content[:20] ..."
        return self.content

class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    chname = models.CharField(max_length=200)
    chpic = models.ImageField(upload_to="vote/%y")
    chcom = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)
    
    def __str__(self):
        return f"{self.topic}-{self.chname}"

vote/views.py
import django
from django.shortcuts import redirect, render
from .models import Topic, Choice
from django.utils import timezone

def index(request):
    t = Topic.objects.all()
    t = t.order_by('-pubdate')
    context = {
        "tset" : t,
    }
    
    return render(request, "vote/index.html", context)

def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t" : t,
        "cset" : c
    }
    return render(request, "vote/detail.html", context)

def vote(request, tpk):

    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("ch")
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    return redirect("vote:detail", tpk)

def cancel(request, tpk):
    t = Topic.objects.get(id=tpk)
    t.voter.remove(request.user)
    # cset = t.choice_set.all()
    # for i in cset:
    #     if request.user in i.choicer.all():
    #         i.choicer.remove(request.user)

    #유저 입장에서 내가 고른 보기들 중 topic이 t인 것을 고르기
    request.user.choice_set.get(topic=t).choicer.remove(request.user)
    return redirect("vote:detail", tpk)

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        cn = request.POST.getlist("cname")
        cp = request.FILES.getlist("cpic")
        cc = request.POST.getlist("ccom")
        
        if len(cn) > 1:
            t = Topic(subject=s, content=c, maker=request.user, pubdate=timezone.now())
            t.save()
            for name, pic, com in zip(cn, cp, cc):
                Choice(topic=t, chname=name, chpic=pic, chcom=com).save()
            return redirect("vote:index")

    return render(request, "vote/create.html")
# Create your views here.

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}

<div class="container mt-5 mb-5">
    <h1><b>New Topic</b></h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="sub" class="form-control mt-3" placeholder="주제를 입력하세요"><br>
        <textarea name="con" class="form-control" placeholder="내용을 입력하세요" style="height: 150px;"></textarea><br>

        <div class="text-center">
            <button type="button" onclick="make()" class="btn btn-secondary">항목추가</button>
            <button class="btn btn-primary">생성하기</button>
        </div>

        <div id="here" class="row mt-3"></div>

    </form>

    <script>
        function make(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute('class', 'col-lg-4 mt-4');
            n.innerHTML = '<div class="card" style="padding: 20px;">\
                <input type="text" name="cname" class="form-control" placeholder="보기의 이름을 입력하세요"><br>\
                <input type="file" name="cpic"  class="form-control"><br>\
                <textarea name="ccom" class="form-control" placeholder="보기의 내용을 입력하세요"></textarea>\
            </div>';
            d.appendChild(n);

        }
    </script>

</div>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}
{% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>{{t.subject}}</b></h1>

        <div class="row">
            <div class="col-lg-8">
                <textarea class="form-control" style="height: 300px;" disabled>{{t.content}}</textarea>
            </div>
            <div class="col-lg-4 text-center" style="margin: auto;">
                <img src="{{t.maker.getpic}}" width="100%">
                <div class="mt-4">
                    <h5>made by <b>{{t.maker}}</b></h5>
                </div>
                
            </div>

        </div>    
        {% if user in t.voter.all %}
            {% csrf_token %}
            <div class="row mt-5">
                {% for i in cset %}
                    <div class="col-lg-4">
                        
                        
                        <img src="{{i.chpic.url}}" width="100%">

                        <div class="text-center mt-3">
                            <h4><b>{{i.chname}}</b></h4>

                        </div>

                        <textarea class="form-control" disabled>{{i.chcom}}</textarea>
                        
                        <div class="progress mt-3">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: {{i.choicer.all.count|div:t.voter.all.count|mul:100}}">{{i.choicer.all.count|div:t.voter.all.count|mul:100|floatformat:"0"}}%</div>
                        </div>

                    </div>

                {% endfor %}

            </div>

            <div class="text-center mt-5">
                <a href="{% url 'vote:cancel' t.id %}" class="btn btn-secondary btn-lg">투표취소</a>
            </div>

        {% else %}
            <form method="post" action="{% url 'vote:vote' t.id %}">
                {% csrf_token %}
                <div class="row mt-5">
                    {% for i in cset %}
                        <div class="col-lg-4">
                            <div class="text-center mb-3">
                                <input class="form-check-input" type="radio" name="ch" value="{{i.id}}" {% if forloop.first %}checked{% endif %}>
                            </div>    
                            <img src="{{i.chpic.url}}" width="100%">
                            <div class="text-center mt-3">
                                <h4><b>{{i.chname}}</b></h4>

                            </div>

                            <textarea class="form-control" disabled>{{i.chcom}}</textarea>
                        </div>
                    {% endfor %}

                </div>

                <div class="text-center mt-5">
                    <button class="btn btn-dark btn-lg">투표하기</button>
                </div>
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>투표함</b></h1>

        <div class="text-end">
            <a href="{% url 'vote:create' %}" class="btn btn-dark btn-lg">New Topic</a>

        </div>


        <div class="row">
            {% for i in tset %}
                <div class="col-lg-4 mt-3">
                    <div class="card" style="width: 100%;">
                        <img src="{{i.maker.getpic}}" class="card-img-top" width="100%">
                        <div class="card-body" {% if user in i.voter.all %} style="background-color:beige ;"{% endif %}>
                            <h5 class="card-title">{{i.subject}}</h5>
                            <p class="card-text">{{i.summary}}</p>
                            <div class="text-center">
                                <a href="{% url 'vote:detail' i.id %}" class="btn btn-primary btn-lg">{% if user in i.voter.all %}결과보기{% else %}투표하기{% endif %}</a>
                            </div>
                        </div>
                    </div>
                </div>
         
            {% endfor %}
        </div>

    </div>
{% endblock %}