acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('lgout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('deply/<bpk>/<rpk>', views.deply, name="deply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('pdfread/', include('pdfread.urls')),
    path('vote/', include('vote.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    comment = models.TextField()
    point = models.IntegerField(default=0)
    age = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y/%m")
    
    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"
# Create your models here.

acc/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from .models import User
from django.contrib.auth.hashers import check_password
from django.contrib import messages

def index(request):
    return render(request, "acc/index.html")

def login_user(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        user = authenticate(username=un, password=up)

        if user:
            messages.success(request, "로그인 성공!")
            login(request, user)
            return redirect("acc:index")

        else:
            messages.error(request, "계정정보가 일치하지 않습니다.")
    return render(request, "acc/login.html")

def logout_user(request):
    messages.warning(request, "로그아웃 되었습니다.")
    logout(request)
    return redirect("acc:index")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        ua = request.POST.get("uage")
        uc = request.POST.get("ucom")
        ui = request.FILES.get("upic")
        try:
            User.objects.create_user(username=un, password=up, age=ua, comment=uc, pic=ui)
            return redirect("acc:login")
        except:
            messages.error(request, "이미 존재하는 계정입니다.")
    return render(request, "acc/signup.html")

def profile(request):
    return render(request, "acc/profile.html")

def delete(request):
    pwck = request.POST.get("pwck")
    up = request.user.password
    if check_password(pwck, up):
        request.user.pic.delete()
        request.user.delete()
        return redirect("acc:login")
    else:
        messages.error(request, "잘못된 접근입니다.")    
    return redirect("acc:profile")

def update(request):
    u = request.user
    if request.method == "POST":
        up = request.POST.get("upass")
        ua = request.POST.get("uage")
        uc = request.POST.get("ucom")
        ui = request.FILES.get("upic")
        if up:
            u.set_password(up)
        u.age = ua
        u.comment = uc
        if ui:
            u.pic.delete()
            u.pic = ui
        u.save()
        login(request, u)
        return redirect("acc:profile")

    return render(request, "acc/update.html")
# Create your views here.

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">로그인성공</h1>
            <p class="col-md-8 fs-4"><b>{{user}}</b>님 환영합니다!</p>
            <a href="{% url 'board:index' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">BOARD</button></a>    
    </div>
</div>
{% endblock %}

{% block noath %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
            <p class="col-md-8 fs-4">로그인해주세요!</p>
            <a href="{% url 'acc:login' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">LOGIN</button></a>
   
    </div>
</div>

{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block noath %}

<div class="container mt-5 mb-5">
    <h1><b>로그인</b></h1>
    <form method="post">
        {% csrf_token %}
    <div class="mt-5">
        <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME" style="font-weight: bold;">
        <input type="password" name="upass" class="form-control mt-4" placeholder="INPUT PASSWORD" style="font-weight: bold;">
    </div>
    <div class="text-end mt-4">
        <button class="btn btn-dark">LOGIN</button>
    </div>
</div>
</form>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
<div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
    <h1><b>프로필</b></h1>

    <div class="text-center mt-5">
        <img src="{{user.getpic}}" class="rounded-circle" width="70%">
    </div>

    <div class="mb-3 mt-5">
        <label class="form-label" >USERNAME</label>
        <input type="text" disabled class="form-control" value="{{request.user}}" style="font-weight: bold;" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label class="form-label">AGE</label>
        <input type="text" style="font-weight: bold;" value="{{request.user.age}}" disabled class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label class="form-label">POINT</label>
        <input type="text" style="font-weight: bold;" value="{{request.user.point}}" disabled class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label class="form-label">COMMENT</label>
        <textarea class="form-control" disabled style="font-weight: bold; height: 100px;">{{request.user.comment}}</textarea>
    </div>

    <div class="text-end">
        <a href="{% url 'acc:update' %}" class="btn btn-dark">정보수정</a>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            계정삭제
        </button>
    </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b>계정 삭제 알림</b></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>정말로 삭제하시겠습니까?</h5>
                <form method="post" action="{% url 'acc:delete' %}">
                {% csrf_token %}
                    <b>패스워드 확인</b> <input type="password" name="pwck" class="form-control mt-2">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-danger" style="font-weight: bold; font-family:monospace;">계정삭제</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}

{% block noath %}
<div class="container mt-5 mb-5" style="font-weight: bold; font-size: 20px;">
    <h1><b>회원가입</b></h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label for="exampleInputEmail1" class="form-label">USERNAME</label>
            <input type="text" class="form-control" name="uname" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">PASSWORD</label>
            <input type="password" class="form-control" name="upass" id="exampleInputPassword1">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">AGE</label>
            <input type="number" class="form-control" name="uage" id="exampleInputPassword1">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">COMMENT</label>
            <textarea class="form-control" name="ucom"></textarea>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">USERPIC</label>
            <input type="file" class="form-control" name="upic" id="exampleInputPassword1">
        </div>
        <div class="mt-4 text-end">
            <button type="submit" class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
        </div>
    </form>
</div>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}

{% block con %}
<div class="container mt-5 mb-5"  style="font-size: 20px; font-weight: bold;">
    <h1><b>정보수정</b></h1>
    <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" class="form-control" name="uname" value="{{request.user}}" disabled id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">PASSWORD</label>
            <input type="password" class="form-control" name="upass" id="exampleInputPassword1">
        </div>
        <div class="mb-3">
            <label class="form-label">AGE</label>
            <input type="number" class="form-control"  name="uage" value="{{request.user.age}}" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" name="ucom">{{request.user.comment}}</textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">USERPIC</label>
            <input type="file" class="form-control" name="upic" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="text-end">
            <a href="{% url 'acc:profile' %}"><button type="button" class="btn btn-dark">BACK</button></a>
            <button class="btn btn-dark">UPDATE</button>
        </div>
    </form>
</div>
{% endblock %}