acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('lgout/', views.logout_user, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('deply/<bpk>/<rpk>', views.deply, name="deply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('pdfread/', include('pdfread.urls')),
    path('vote/', include('vote.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")
    pubdate = models.DateTimeField() 

    def __str__(self):
        return self.subject
    def summary(self):
        if len(self.content) > 100:
            return f"{self.content[:100]}"
        return self.content

class Reply(models.Model):
    b = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    pubdate = models.DateTimeField()

    def __str__(self):
        return f"{self.b}_{self.replyer}"

board/views.py
from django.shortcuts import redirect, render
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages

def index(request):
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            messages.error(request, "잘못된 접근입니다.") 
            b = Board.objects.all()
    else:
        b = Board.objects.all()
    b = b.order_by('-likey')
    page = request.GET.get("page", 1)
    pag = Paginator(b, 10)
    obj = pag.get_page(page)
    context = {
        "bset" : obj,
        "cate" : cate,
        "kw" : kw

    }
    return render(request, "board/index.html", context)

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b" : b,
        "rset" : r
    }
    return render(request, "board/detail.html", context)

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        messages.error(request, "삭제에 실패하였습니다.")
    return redirect("board:index")

def create(request):
    if request.method == "POST":
        us = request.POST.get("usub")
        uc = request.POST.get("ucon")
        Board(subject=us,content=uc, writer=request.user, pubdate=timezone.now()).save()
        return redirect("board:index")
    return render(request, "board/create.html")

def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if request.user != b.writer:
        messages.error(request, "잘못된 접근입니다.")
        return redirect("board:index")
    else:   
        if request.method == "POST":
            us = request.POST.get("usub")
            uc = request.POST.get("ucon")
            b.subject = us
            b.content = uc
            b.save()
            return redirect("board:detail", bpk)
    context = {
        "b" : b
    }
    return render(request, "board/update.html", context)

def creply(request, bpk):
    c = request.POST.get("com")
    b = Board.objects.get(id=bpk)
    Reply(b=b, replyer=request.user, comment=c, pubdate=timezone.now()).save()
    return redirect("board:detail", bpk)

def deply(request, bpk,rpk):
    r = Reply.objects.get(id=rpk)
    if request.user == r.replyer:
        messages.error(request, "잘못된 접근입니다.")
    r.delete()
    return redirect("board:detail", bpk)

def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user)
    return redirect("board:detail", bpk)

def unlikey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user)
    return redirect("board:detail", bpk)
# Create your views here.

templates/board/create.html
{% extends 'base.html' %}

{% block con %}
<div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
    <h1><b>게시글 작성</b></h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">SUBJECT</label>
            <input type="text" class="form-control" name="usub">
        </div>
        <div class="mb-3">
            <label class="form-label">WRITER</label>
            <input type="text" class="form-control" value="{{ user }}" disabled>
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" name="ucon" style="height: 100px;"></textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">생성</button>
        </div>
    </form>
</div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}

{% block con %}
    <div class="container mt-5 md-5">
        <h1 class="text-"><b>{{b.subject}}</b></h1>
        <div class="row mt-5">
            <div class="col-lg-8">
                <textarea class="form-control" disabled style="height: 300px;">{{b.content}}</textarea>
            </div>

            <div class="col-lg-4 text-center" style="margin: auto;">
                <img src="{{b.writer.getpic}}" width="200px">
                <div class="mt-3" style="font-size: 20px;">
                    wirrten by <b>{{b.writer}}</b>
                </div>
            </div>

            <div class="text-cneter">
                {{b.pubdate | date:'Y년 n월 j일 G:i'}}
            </div>
        <div class="text-end mt-4">
            <a href="{% url 'board:index'%}" class="btn btn-dark">BACK</a>
            {% if user == b.writer %}
                <a href="{% url 'board:update' b.id %}" class="btn btn-secondary">MOD</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    DEL
                </button>
            {% endif %}

            <div class="mt-3">
                {% if user in b.likey.all %}
                    <a href="{% url 'board:unlikey' b.id %}" class="btn btn-danger">취소</a>
                {% else %}
                    <a href="{% url 'board:likey' b.id %}" class="btn btn-primary">좋아요</a>
                {% endif %}
            </div>
        </div>
    </div>

    

    <hr>
       <div class="container">
            <form method="post" action="{% url 'board:creply' b.id %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-10 text-end">
                        <input type="text" class="form-control" name="com" placeholder="댓글을 작성하세요">
                    </div>
                    <div class="col-lg-2">
                        <button class="btn btn-dark">댓글작성</button>
                    </div>
                </div>
            </form>
            {% if rset %}
                {% for i in rset %}
                    <div class="row mt-5">
                    <div class="col-lg-3"><img src="{{i.replyer.getpic}}" width=80%">
                        <div class="mt-3 text-center"><b>{{i.replyer}}</b></div>
                    </div>
               
                    <div class="col-lg-9" style="margin: auto;">
                        <textarea class="form-control" disabled style="height: 200px;">{{i.comment}}</textarea>
                        <div class="text-end">
                            {% if user == i.replyer %}
                                <a href="{% url 'board:deply' b.id i.id %}"><button class="btn btn-danger mt-2">댓글삭제</button></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}

            {% endif %}
        
        </div> 

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">게시글 삭제</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                    <div class="modal-body">
                        정말 삭제하시겠습니까?
                        </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-dark" data-bs-dismiss="modal">CLOSE</button>
                        <a href="{% url 'board:delete' b.id %}"><button type="button" class="btn btn-danger">DEL</button></a>
                    </div>
                </div>
            </div>
     </div>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}

{% block con %}
{% load mathfilters %}
<div class="container mt-5 md-5">
    <h1><b>게시판</b></h1>
    <div class="text-end">
        <a href="{% url 'board:create' %}" class="btn btn-dark">CREATE</a>
    </div>

    <table class="table mt-2">
        <thead>
            <tr>
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">WRITER</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            
                {% if bset %}
                    {% for i in bset %}
                    <tr>
                        <th scope="row">{{ bset.start_index|add:forloop.counter0}}</th>
                        <td><a class="sub" href="{% url 'board:detail' i.id%}">{{i.subject}}</a></td>
                        <td>{{i.summary}}</td>
                        <td>{{i.writer}}</td>
                        <td>{{i.likey.all.count}}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    {% if kw %}
                    <tr class="text-center">
                        <th colspan="5">검색결과가 없습니다.</th>
                    </tr>
                    {% else %}
                    <tr class="text-center">
                        <th colspan="5">게시글을 작성해주세요.</th>
                    </tr>
                    {% endif %}
                    
                {% endif %}

        </tbody>
    </table>

    <nav aria-label="Page navigation example" class="mt-5">
        <ul class="pagination justify-content-center">
    
            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&cate={{cate}}&kw={{kw}}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}
            
    
            {% for i in bset.paginator.page_range %}
                {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
                    <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}
    
    
            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}
    
    
        </ul>
    </nav>

    <form>
        <div class="row mt-5 mb-5">
            <div class="col-lg-2">            
                <select name="cate" class="form-select" aria-label="Default select example">
                    <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == "wri" %} selected {% endif %}>글쓴이</option>
                    <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                </select>
            </div>

            <div class="col-lg-9">
                <input type="text" name="kw" class="form-control" value="{{kw}}">
            </div>
            <div class="col-lg-1">
                <button class="btn btn-dark">검색</button>
            </div>
        </div>
    </form>
    <style>
        a.sub{
            text-decoration: none;
            font-size: 18px;
            color: black;
        }
        a.sub:hover{
            font-weight: bold;
            color: red;
            font-size: 18px;
        }
    </style>
{% endblock %}

templates/board/update.html
{% extends 'base.html' %}

{% block con %}
<div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
    <h1><b>게시글 수성</b></h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">SUBJECT</label>
            <input type="text" class="form-control" name="usub" value="{{ b.subject }}">
        </div>
        <div class="mb-3">
            <label class="form-label">WRITER</label>
            <input type="text" class="form-control" value="{{ b.writer }}" disabled>
        </div>
        <div class="mb-3">
            <label class="form-label">CONTENT</label>
            <textarea class="form-control" name="ucon" style="height: 100px;">{{b.content}}</textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">MOD</button>
        </div>
    </form>
</div>
{% endblock %}